### ISSUE TITLE
ColorStyle cases mis-spell 'Background'

### ISSUE THREAD

**Issue by sstadelman** [SAP/cloud-sdk-ios-fiori#152]
In **ColorStyle.swift**, the suffix `Background` is frequently mis-spelled as `Backgrond`.  Can these be fixed?

<img width="297" alt="Screen Shot 2020-10-15 at 9 39 33 AM" src="https://user-images.githubusercontent.com/377404/96160232-89063480-0eca-11eb-8bd2-6579a19181ed.png">

**Comment by justinguo** [comment]
Sure thing. I will fix these names soon.
