### ISSUE TITLE
Donut chart type is not centred in Cell when using FUIChartPlotTableViewCell

### ISSUE THREAD

**Issue by alisdair73** [SAP/cloud-sdk-ios-fiori#233]
**Describe the bug**
When using the Donut type chart in a Table View, the chart appears left aligned rather than centred. All other charts seem to with fill the cell width so appear to be centred.

**To Reproduce**
You can just use the sample code from the Chart Plot example in the Fiori Mentor and set the chart type to .donut

I have used both 5.1.x and 6.0.x versions of the SDK for this with the same result.

**Expected behaviour**
Chart is centre aligned - so the behaviour is the same as when using the Chart Floorplan

**Screenshots**
Testing using the cloud-sdk-ios-fiori examples shows the same behaviour. That said, if you up the length ratio with the slider in the example app it does finally align once the Diameter == cell width. 

Example from Floorplan

![image](https://user-images.githubusercontent.com/503165/113678658-3c294b00-9702-11eb-9761-2cd0df8dce77.png)

Example from Table Cell

![image](https://user-images.githubusercontent.com/503165/113678726-4f3c1b00-9702-11eb-97af-d19867494c78.png)

**Additional context**
I did see that the charts in both the latest 5 and 6 releases were SwiftUI based - is the codeline the same as in the github repo? Very cool stuff!

Please let me know if you need any more info - I have a sample project if that would help?

Al Templeton

**Comment by billzhou0223** [comment]
Hi @alisdair73, thanks for checking-in! 

The fix is merged in this repo. You are right SAPFiori is using chart components in this github repo but in order for the fix to be included we need to update the commit head in SAPFiori. If you also need the fix in SAPFiori please let me know the version you are using so we can update corresponding branch to include this fix.

**Comment by alisdair73** [comment]
Hi Bill! Nice to hear from you - thanks for getting this sorted so quickly. I'm currently bouncing between the latest 5.x and 6.x releases - though that said, at this stage i'd be looking to go-live at my current client with the 5.x framework.  Whats the current thinking regarding 5->6?

While I was setting up some examples with the Chart floorplan I discovered the Object Page and Object List floorplans - that's some pretty cool stuff - are there any plans for some examples apps based on these to use as a guide- I was able to get something working but not 100% sure I'm doing it right (ditto for the multi user onboarding - I can really use this at my current client but not clear on how to integrate it in) - Thanks again!!

**Comment by billzhou0223** [comment]
> Hi Bill! Nice to hear from you - thanks for getting this sorted so quickly. I'm currently bouncing between the latest 5.x and 6.x releases - though that said, at this stage i'd be looking to go-live at my current client with the 5.x framework. Whats the current thinking regarding 5->6?
> 
> While I was setting up some examples with the Chart floorplan I discovered the Object Page and Object List floorplans - that's some pretty cool stuff - are there any plans for some examples apps based on these to use as a guide- I was able to get something working but not 100% sure I'm doing it right (ditto for the multi user onboarding - I can really use this at my current client but not clear on how to integrate it in) - Thanks again!!

Yes we will be adding these examples to Mentor app in the near future. Stay tunned for new mentor release :)
