### ISSUE TITLE
Support sap.ui.core.format.NumberFormat substitutions

### ISSUE THREAD

**Issue by sstadelman** [SAP/cloud-sdk-ios-fiori#29]
Integration Cards handlebar replacement should support JS transformations with sap.ui.core.format.NumberFormat options.

https://openui5.hana.ondemand.com/#/api/sap.ui.core.format.NumberFormat

Supported per specification: 
https://openui5.hana.ondemand.com/test-resources/sap/ui/integration/demokit/cardExplorer/webapp/index.html#/learn/formatters

**Comment by MarcoEidinger** [comment]
Not relevant anymore
