### ISSUE TITLE
[Security] Workflow pr_only.yml is using vulnerable action wagoid/commitlint-github-action

### ISSUE THREAD

**Issue by qazaqstan2025** [SAP/cloud-sdk-ios-fiori#390]
The workflow pr_only.yml is referencing action wagoid/commitlint-github-action using references v1. However this reference is missing the commit [bf83d2b35c4177779d047f464b48d9907f2c5201](https://github.com/wagoid/commitlint-github-action/commits/bf83d2b35c4177779d047f464b48d9907f2c5201) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by billzhou0223** [comment]
Resolved by #391
