### ISSUE TITLE
KPIItem for VoiceOver accessibility always pronounced as button, `.accessibilityRemoveTraits([.isButton])` has no effect

### ISSUE THREAD

**Issue by dzmitry-antonenka-sap** [SAP/cloud-sdk-ios-fiori#436]
**Describe the bug**
KPIItem for VoiceOver accessibility always pronounced as button, `.accessibilityRemoveTraits([.isButton])` has no effect

**To Reproduce**
1. Enable `Accessibility` -> `Voice Over`
2. Run Examples.xcodeproj app and navigate to `Core Elements` -> `KPI`
3. Observe that KPI pronounced as button, even no action is available, `.accessibilityRemoveTraits([.isButton])` doesn't help

**Expected behavior**
I expect API to provide accessibility traits to work (e.g. `.accessibilityRemoveTraits([.isButton])`), or option to control via initializer (e.g. nil action handle means no button trait)

Mobile (please complete the following information):

Device: iPhone 8
OS: iOS 15.5
Swift Package Product: FioriSwiftUICore
Swift Package Version: 2.1.0, main branch, commit https://github.com/SAP/cloud-sdk-ios-fiori/commit/a82de93715b34e0b834f1993c85e3488018f41bc
Xcode Version: Version 13.4 (13F17a), toolchain Xcode Version 13.4 (13F17a)
FioriSwiftUI / cloud-sdk-ios-fiori 2.1.0

**Additional context**

**Comment by MarcoEidinger** [comment]
@billzhou0223 I looked at this and based on my testing it appears that SwiftUI does not allow to remove `isButton` trait from a `Button`.

This can be reproduced in this standalone example:

```swift
Button("What is it?", action: {}).accessibilityRemoveTraits([.isButton])
```

https://user-images.githubusercontent.com/4176826/174910964-21e97588-6246-4868-b546-3236f6fa60ae.mov

`FioriSwiftUICore.KPIItem` can have an action but it's optional. Instead of always using `Button` internally we might want to use `Button` only if there is an action available.

Example:

```swift
extension KPIItem: View {
    public var body: some View {
        if let buttonAction = action {
            Button(action: action ?? {}) {
                VStack(alignment: .center, spacing: 2) {
                    kpi
                    subtitle
                }
                .frame(maxWidth: 216)
            }.buttonStyle(ButtonContainerStyle())
        } else {
            VStack(alignment: .center, spacing: 2) {
                kpi
                subtitle
            }
            .frame(maxWidth: 216)
        }
    }
}
```

**Comment by billzhou0223** [comment]
Good point. Updated it based on Marco's suggestion.
