### ISSUE TITLE
WatchOS support

### ISSUE THREAD

**Issue by dzmitry-antonenka** [SAP/cloud-sdk-ios-fiori#506]
Could you please enable WatchOS support so frameworks can be used for watch application development? At the moment only iOS platform is supported.

**Comment by MarcoEidinger** [comment]
`FioriThemeManager` is supported on watchOS. `FioriSwiftUICore` and `FioriCharts` are not supported on watchOS as the UI controls were not specifically designed for watchOS.

For requirements from your team concerning the watchOS roadmap, including SAP BTP SDK for iOS frameworks, please get in touch with me via corporate email to follow our internal feature request procedures.
