### ISSUE TITLE
FioriButtonStyle is not accessible 

### ISSUE THREAD

**Issue by ravitejasap** [SAP/cloud-sdk-ios-fiori#607]
**Describe the bug**
For the example project, try adding the package in Package dependencies instead of directly pointing in the frameworks.
Unable to build the project as FioriButtonStyles are missing.

Same issue when adding this package to any project and try accessing `AnyFioriButtonStyle`, `FioriPrimaryButtonStyle`, e.t.c

**Expected behavior**
We should be able to build the project when adding this package in Package dependencies in XCode.

**Screenshots**
<img width="1213" alt="image" src="https://github.com/SAP/cloud-sdk-ios-fiori/assets/120622460/8aeb4ff9-df00-4cad-83ba-69ae108930ce">

<img width="1210" alt="image" src="https://github.com/SAP/cloud-sdk-ios-fiori/assets/120622460/db1a3d58-70ac-4867-9e53-621c8712bce7">

**Mobile (please complete the following information):**
 - Swift Package Version: 3.3.0
 - Xcode Version: 15.0.1

**Comment by billzhou0223** [comment]
Hi @ravitejasap,

These button styles were added after the 3.3.0 release and only available in main branch. So you need to change the dependency rule to main branch instead of a specific version.
