### ISSUE TITLE
Can't use UIViewRepresentable with widgets in iOS 14

### ISSUE THREAD

**Issue by alisdair73** [SAP/cloud-sdk-ios-fiori#87]
Hi All

Great library - really having fun with this!

Was trying some of the Charts in various size widgets. Found that the micro charts worked well but the more complex Charts wouldn't render - see screen grab - .line, .column etc.

Found that in the GridLinesAndChartView.swift file there is a view called Background that is using UIViewRepresentable - this won't render as a widget - I have tested this by removing the Background view from the ZStack created in createBody.

Not sure how easy this will be to fix as there are a bunch of gestures attached to Background - but prob don't need these for a widget version?

Let me know if you need any more information

Al T.

![image](https://user-images.githubusercontent.com/503165/89034181-cbb07a00-d37b-11ea-8ebf-1abca467cb24.png)

**Comment by MarcoEidinger** [comment]
Hi @alisdair73 , I am happy to hear you like the chart library and I am stoked to see your progress on [Twitter](https://twitter.com/alisdair73/status/1288762803327655936) !!!

![EeKa77NUMAAWyNk](https://user-images.githubusercontent.com/4176826/89034916-c527f100-d2ee-11ea-9e42-6b51dba60794.jpeg)

Also thank you so much for root cause analysis! I think we are good with the provided info but if not we'll get back to you :)

Happy Friday!

**Comment by MarcoEidinger** [comment]
Reproducible with https://github.com/MarcoEidinger/FioriChartsInWidgets

<img width="1340" alt="xcode12_beta3" src="https://user-images.githubusercontent.com/4176826/89039230-885ff800-d2f6-11ea-8f79-56a6ba7cf6ca.png">

**Comment by shengxu7** [comment]
The latest PR for branch main fixed this issue. Just need to make sure model's userInteractionEnabled is false so the UIViewRepresentable will not be rendered.
<img width="478" alt="Screen Shot 2020-07-31 at 4 20 26 PM" src="https://user-images.githubusercontent.com/61521732/89087662-d05c3a80-d349-11ea-866a-dbfc458699dc.png">

**Comment by MarcoEidinger** [comment]
Bug fix included in release [0.5.5](https://github.com/SAP/cloud-sdk-ios-fiori/releases/tag/0.5.5)

To reiterate `ChartModel.userInteractionEnabled` requires to be `false` (its default) in this case

**Comment by alisdair73** [comment]
Thanks guys - that was super fast - have just updated my package dependencies to 0.5.5. and works beautifully!

Awesome!
